FROM node:lts

RUN curl -fsSL get.docker.com | sh

RUN apt-get update && apt-get install -y \
    chromium \
    chromium-driver \
    jq \
    zip

RUN npm install -g npm

COPY stages stages

WORKDIR /app

USER node
