version: 2.1
jobs:
  pipeline-job:
    docker:
      - image: docker/compose
    working_directory: /app
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - add_ssh_keys:
          fingerprints:
            - "68:57:52:54:24:68:1c:45:ce:95:57:f3:ef:de:23:9a"
      - run:
          name: Pipeline
          command: |
            pwd
            ls -la
            docker -v
            docker compose -f .devcontainer/docker-compose.yml --env-file app-2/.env run --rm app-2
workflows:
  pipeline-workflow:
    jobs:
      - pipeline-job