version: 2.1
jobs:
  pipeline-job:
    docker:
      - image: node:lts
    working_directory: /app
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - add_ssh_keys:
          fingerprints:
            - "68:57:52:54:24:68:1c:45:ce:95:57:f3:ef:de:23:9a"
      - run:
          name: Build
          command: |
            npm run build
      - run:
          name: Test
          command: |
            npm run test
      - run:
          name: Start
          command: |
            npm run start
      - run:
          name: Archive
          command: |
            npm run archive
      - run:
          name: Deploy
          command: |
            npm run deploy
workflows:
  pipeline-workflow:
    jobs:
      - pipeline-job