version: 2.1

# the default pipeline parameters, which will be updated according to
# the results of the path-filtering orb
parameters:
  run-build-app-1-job:
    type: boolean
    default: false
  run-build-app-2-job:
    type: boolean
    default: false

jobs:
  app-1-workflow:
    docker:
      - image: ypolosov/agnostic-pipeline
    environment:
      PROJECT_DIR: app-1
      REPOSITORY_URL: https://github.com/ypolosov/generic-pipelines-using-docker.git
    working_directory: /app
    resource_class: small
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - add_ssh_keys:
          fingerprints:
            - "68:57:52:54:24:68:1c:45:ce:95:57:f3:ef:de:23:9a"
      - run:
          name: Clone
          command: /stages/01_clone.sh
      - run:
          name: Build
          command: /stages/02_build.sh
      - run:
          name: Test
          command: /stages/03_test.sh
      - run:
          name: Archive
          command: |
            export DOCKER_PASSWORD="$DOCKER_PASSWORD"
            /stages/04_archive.sh
      - run:
          name: Deploy
          command: /stages/05_deploy.sh
      # - run:
      #     name: Test
      #     command: /stages/ssh_test.sh
  app-2-workflow:
    docker:
      - image: ypolosov/agnostic-pipeline
    environment:
      PROJECT_DIR: app-2
      REPOSITORY_URL: https://github.com/ypolosov/generic-pipelines-using-docker.git
    working_directory: /app
    resource_class: small
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - add_ssh_keys:
          fingerprints:
            - "68:57:52:54:24:68:1c:45:ce:95:57:f3:ef:de:23:9a"
      - run:
          name: Clone
          command: /stages/01_clone.sh
      - run:
          name: Build
          command: /stages/02_build.sh
      - run:
          name: Test
          command: /stages/03_test.sh
      - run:
          name: Archive
          command: |
            export DOCKER_PASSWORD="$DOCKER_PASSWORD"
            /stages/04_archive.sh
      - run:
          name: Deploy
          command: /stages/05_deploy.sh
      # - run:
      #     name: Test
      #     command: /stages/ssh_test.sh

# here we specify our workflows, most of which are conditionally
# executed based upon pipeline parameter values. Each workflow calls a
# specific job defined above, in the jobs section.
workflows:
  # when pipeline parameter, run-build-service-1-job is true, the
  # build-service-1 job is triggered.
  app-1:
    when: << pipeline.parameters.run-build-app-1-job >>
    jobs:
      - app-1-workflow

  # when pipeline parameter, run-build-service-2-job is true, the
  # build-service-2 job is triggered.
  app-2:
    when: << pipeline.parameters.run-build-app-2-job >>
    jobs:
      - app-2-workflow