name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  pipeline-job:

    runs-on: ubuntu-latest
    container: node:lts
    env:
      PROJECT_DIR: app-1

    steps:
    - uses: actions/checkout@v3

    - name: Docker in Docker
      run: |
        curl -fsSL get.docker.com | sh

    - name: Config
      run: |
        CONFIG_PATH="$PROJECT_DIR/.env"
        cat "${CONFIG_PATH}" >> $GITHUB_ENV
        echo "$GITHUB_ENV"

    - name: Ci
      run: |
        ./agnostic-pipeline/stages/01_ci.sh

    - name: Build
      run: |
        ./agnostic-pipeline/stages/02_build.sh

    - name: Test
      run: |
        ./agnostic-pipeline/stages/03_test.sh

    - name: Archive
      run: |
        export DOCKER_PASSWORD="${{secrets.DOCKER_PASSWORD}}"
        ./agnostic-pipeline/stages/04_archive.sh






    # - name: Install SSH Key
    #   uses: shimataro/ssh-key-action@v2
    #   with:
    #     key: ${{ secrets.SSH_PRIVATE_KEY }} 
    #     known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    # - name: Deploy
    #   run: |
    #     mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
    #     chmod 700 ~/.ssh
    #     chmod 644 ~/.ssh/known_hosts
    #     ssh-keyscan 158.160.40.229 >> ~/.ssh/known_hosts
    #     ./agnostic-pipeline/stages/05_deploy.sh

    # - name: executing remote ssh commands using password
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: 158.160.40.229
    #     username: ypolosov
    #     key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     script: |
    #       ssh-keyscan 158.160.40.229 >> ~/.ssh/known_hosts
    #       ssh ypolosov@158.160.40.229 hostname -f


    # - name: s1
    #   run: |
    #     cat ${{ secrets.agnostic-pipeline }} | ssh ypolosov@158.160.44.177 "mkdir -p ~/.ssh && touch ~/.ssh/authorized_keys && chmod -R go= ~/.ssh && cat >> ~/.ssh/authorized_keys"
    #     ls -la ~/.ssh
    #     cat ~/.ssh/authorized_keys
    # - name: Install SSH Key
    #   uses: shimataro/ssh-key-action@v2
    #   with:
    #     key: ${{ secrets.SSH_PRIVATE_KEY }} 
    #     known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    # - name: s2
    #   run: |
    #     mkdir -p ~/.ssh
    #     touch ~/.ssh/known_hosts
    #     chmod 644 ~/.ssh/known_hosts
    #     cat ~/.ssh/known_hosts
    # - name: s3
    #   run: |
    #     echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/id_rsa
    # - name: s4
    #   run: |
    #     ssh-keyscan -H 158.160.50.242 >> ~/.ssh/known_hosts
    #     cat ~/.ssh/known_hosts
    # - name: s5
    #   run: |
    #     ssh -vvv ypolosov@158.160.50.242 hostname -f

    - name: Pre-deploy
      id: pre-deploy
      uses: andstor/file-reader-action@v1
      with:
        path: ./agnostic-pipeline/stages/05_deploy.sh

    - name: Deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ env.DEPLOY_HOST }}
        username: ${{ env.DEPLOY_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ env.DEPLOY_PORT }}
        script: |
          ${{ steps.pre-deploy.outputs.contents }}
