name: Docker Image CI

on:
  push:
    branches: [ "master" ]

defaults:
  run:
    working-directory: /app
    
jobs:

  pipeline-job:

    runs-on: ubuntu-latest
    container: node:lts
    env:
      PROJECT_DIR: app-1

    steps:
    - uses: actions/checkout@v3
    - name: My step
      run: |
        echo Hello Github Actions!

    - name: Docker in Docker
      run: |
        curl -fsSL get.docker.com | sh

    - name: Ci
      run: |
        ./agnostic-pipeline/stages/01_ci.sh

    - name: Build
      run: |
        ./agnostic-pipeline/stages/02_build.sh

    - name: Test
      run: |
        ./agnostic-pipeline/stages/03_test.sh

    - name: Archive
      run: |
        export DOCKER_PASSWORD="$DOCKER_PASSWORD"
        ./agnostic-pipeline/stages/04_archive.sh

    - name: Deploy
      run: |
        ./agnostic-pipeline/stages/05_deploy.sh
