name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: node:lts

    steps:
    - uses: actions/checkout@v3
    - name: My step
      run: |
        echo Hello Github Actions!
